# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Stellar
subtitle: '每个人的独立博客 | Designed by xaoxuu'
description: 
keywords:
author: xaoxuu
language: [zh-CN, en, zh-TW]
timezone: ''
avatar: /assets/icon.svg
email: me@xaoxuu.com
favicon: /assets/icon.svg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xaoxuu.com/wiki/stellar
root: /wiki/stellar/
permalink: blog/:year:month:day/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: blog/archives
category_dir: blog/categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 1 # 把文件名称转换为 (1) 小写或 (2) 大写	默认(0)
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: '    '

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: ll
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
  - 'wiki/stellar/README.md'
  - 'wiki/stellar/LICENSE'
  - 'wiki/stellar/.*'
ignore:
  - .DS_Store
  - /**/.DS_Store

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar


# Deployment
## Docs: https://hexo.io/docs/deployment.html
# npm install hexo-deployer-git --save
deploy:
  - type: git
    repo: https://github.com/xaoxuu/xaoxuu.github.io.git
    branch: gh-pages
    message: "Build at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"


########################### Plugins ###########################
# npm i hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 10
  content: false
  icon: /assets/icon.svg
  autodiscovery: true

# npm i hexo-related-popular-posts
# npm uninstall hexo-related-popular-posts
# "hexo-related-popular-posts": "^5.0.1",

# npm i hexo-neat
neat_enable: false

# npm i hexo-all-minifier
all_minifier: true
image_minifier:
  enable: false
  
# npm i hexo-autonofollow
nofollow:
  enable: true
  exclude:
    - xaoxuu.com

archive_generator:
  enabled: true
  per_page: 0
  yearly: false
  monthly: false
  daily: false
  order_by: -date

# https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false
  page_priority: 0.4
  post_priority: 0.6

aplayer:
  meting: true