name: auto deploy # workflow name

on:
  workflow_dispatch:
  push:

jobs:
  build: # job1 id
    name: auto deploy
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    env:
      TZ: Asia/Shanghai  # ✅ 设置时区
    steps:
    - name: Checkout # step1 获取源码
      uses: actions/checkout@v3 # 使用 actions/checkout@v3
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？
    - name: Setup Node.js 22.16.x
      uses: actions/setup-node@master
      with:
        node-version: "22.16.x"
    - name: Generate Public Files
      run: |
        npm i
        npm install hexo-cli -g
        npm run g
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        # deploy_key: ${{ secrets.DEPLOY_KEY }}
        # external_repository: xaoxuu/hexo-theme-stellar-docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'